// // <auto-generated>
// //     Generated by the protocol buffer compiler.  DO NOT EDIT!
// //     source: battleverify.proto
// // </auto-generated>
// #pragma warning disable 1591, 0612, 3021
// #region Designer generated code

// using pb = global::Google.Protobuf;
// using pbc = global::Google.Protobuf.Collections;
// using pbr = global::Google.Protobuf.Reflection;
// using scg = global::System.Collections.Generic;
// /// <summary>Holder for reflection information generated from battleverify.proto</summary>
// public static partial class BattleverifyReflection {

//   #region Descriptor
//   /// <summary>File descriptor for battleverify.proto</summary>
//   public static pbr::FileDescriptor Descriptor {
//     get { return descriptor; }
//   }
//   private static pbr::FileDescriptor descriptor;

//   static BattleverifyReflection() {
//     byte[] descriptorData = global::System.Convert.FromBase64String(
//         string.Concat(
//           "ChJiYXR0bGV2ZXJpZnkucHJvdG8aD2Vycm9yY29kZS5wcm90bxoPc3RhZ2Vk",
//           "YXRhLnByb3RvIm4KEk5vZGVPYmplY3RTZXJ2ZXJfdBIQCghlbnRpdHlJRBgB",
//           "IAEoBRIUCgxub2RlT2JqZWN0SUQYAiABKAUSFQoNbm9kZUN1cnJTdGF0ZRgD",
//           "IAEoBRIZChFub2RlQ2hhbmdlVG9TdGF0ZRgEIAEoBSInChJOb2RlT2JqZWN0",
//           "SW5mb3NSZXESEQoJZHVuZ2VvbklEGAEgASgJInMKEk5vZGVPYmplY3RJbmZv",
//           "c0FjaxIdCgllcnJvckNvZGUYASABKA4yCi5FcnJvckNvZGUSEQoJZHVuZ2Vv",
//           "bklEGAIgASgJEisKDm5vZGVPYmplY3RJbmZvGAMgAygLMhMuTm9kZU9iamVj",
//           "dFNlcnZlcl90IigKFFRyaWdnZXJOb2RlT2JqZWN0UmVxEhAKCGVudGl0eUlE",
//           "GAEgASgFIkcKFFRyaWdnZXJOb2RlT2JqZWN0QWNrEh0KCWVycm9yQ29kZRgB",
//           "IAEoDjIKLkVycm9yQ29kZRIQCghlbnRpdHlJRBgCIAEoBSJJChpOb3RpZnlO",
//           "b2RlT2JqZWN0Q2hhbmdlZEFjaxIrCg5ub2RlT2JqZWN0SW5mbxgBIAMoCzIT",
//           "Lk5vZGVPYmplY3RTZXJ2ZXJfdCIrChdJbnRlcmFjdGlvbkNvbXBsZXRlZFJl",
//           "cRIQCghlbnRpdHlJRBgBIAEoBSJvChdJbnRlcmFjdGlvbkNvbXBsZXRlZEFj",
//           "axIdCgllcnJvckNvZGUYASABKA4yCi5FcnJvckNvZGUSEAoIZW50aXR5SUQY",
//           "AiABKAUSIwoJaW50ZXJCYXNlGAMgASgLMhAuSW50ZXJhY3Rpb25CYXNlIjoK",
//           "FE5vdGlmeU5wY0RvQWN0aW9uQWNrEhAKCGVudGl0eUlEGAEgASgFEhAKCGFj",
//           "dGlvbklEGAIgASgJKo0BChFCYXR0bGVWZXJpZnlNc2dJRBITCg9Ob2RlT2Jq",
//           "ZWN0SW5mb3MQABIVChFUcmlnZ2VyTm9kZU9iamVjdBABEhsKF05vdGlmeU5v",
//           "ZGVPYmplY3RDaGFuZ2VkEAISGAoUSW50ZXJhY3Rpb25Db21wbGV0ZWQQAxIV",
//           "ChFOb3RpZnlOcGNEb0FjdGlvbhAEQhdaFS4uLy4uL3NlcnZlci9wcm90b2Nv",
//           "bGIGcHJvdG8z"));
//     descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
//         new pbr::FileDescriptor[] { global::ErrorcodeReflection.Descriptor, global::StagedataReflection.Descriptor, },
//         new pbr::GeneratedClrTypeInfo(new[] {typeof(global::BattleVerifyMsgID), }, null, new pbr::GeneratedClrTypeInfo[] {
//           new pbr::GeneratedClrTypeInfo(typeof(global::NodeObjectServer_t), global::NodeObjectServer_t.Parser, new[]{ "EntityID", "NodeObjectID", "NodeCurrState", "NodeChangeToState" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::NodeObjectInfosReq), global::NodeObjectInfosReq.Parser, new[]{ "DungeonID" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::NodeObjectInfosAck), global::NodeObjectInfosAck.Parser, new[]{ "ErrorCode", "DungeonID", "NodeObjectInfo" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::TriggerNodeObjectReq), global::TriggerNodeObjectReq.Parser, new[]{ "EntityID" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::TriggerNodeObjectAck), global::TriggerNodeObjectAck.Parser, new[]{ "ErrorCode", "EntityID" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::NotifyNodeObjectChangedAck), global::NotifyNodeObjectChangedAck.Parser, new[]{ "NodeObjectInfo" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::InteractionCompletedReq), global::InteractionCompletedReq.Parser, new[]{ "EntityID" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::InteractionCompletedAck), global::InteractionCompletedAck.Parser, new[]{ "ErrorCode", "EntityID", "InterBase" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::NotifyNpcDoActionAck), global::NotifyNpcDoActionAck.Parser, new[]{ "EntityID", "ActionID" }, null, null, null, null)
//         }));
//   }
//   #endregion

// }
// #region Enums
// /// <summary>
// ///ս����֤��
// /// </summary>
// public enum BattleVerifyMsgID {
//   /// <summary>
//   ///����ɵĻ��Ǵ������Ľڵ����Ϣ��û�д������Ĳ����ͣ�
//   /// </summary>
//   [pbr::OriginalName("NodeObjectInfos")] NodeObjectInfos = 0,
//   /// <summary>
//   ///���󴥷�ĳ���ڵ���¼�
//   /// </summary>
//   [pbr::OriginalName("TriggerNodeObject")] TriggerNodeObject = 1,
//   /// <summary>
//   ///�������������͡��ڵ��״̬�ı䣨��ɱ����ɣ������ĸ��ڵ���ɻ���״̬�ı��ˣ�
//   /// </summary>
//   [pbr::OriginalName("NotifyNodeObjectChanged")] NotifyNodeObjectChanged = 2,
//   /// <summary>
//   ///���󽻻�
//   /// </summary>
//   [pbr::OriginalName("InteractionCompleted")] InteractionCompleted = 3,
//   /// <summary>
//   ///֪ͨNPC�ƶ�
//   /// </summary>
//   [pbr::OriginalName("NotifyNpcDoAction")] NotifyNpcDoAction = 4,
// }

// #endregion

// #region Messages
// /// <summary>
// ///////////////////////////////////////////////
// ///�����ڵ����Ϣ
// /// </summary>
// public sealed partial class NodeObjectServer_t : pb::IMessage<NodeObjectServer_t>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<NodeObjectServer_t> _parser = new pb::MessageParser<NodeObjectServer_t>(() => new NodeObjectServer_t());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<NodeObjectServer_t> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[0]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectServer_t() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectServer_t(NodeObjectServer_t other) : this() {
//     entityID_ = other.entityID_;
//     nodeObjectID_ = other.nodeObjectID_;
//     nodeCurrState_ = other.nodeCurrState_;
//     nodeChangeToState_ = other.nodeChangeToState_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectServer_t Clone() {
//     return new NodeObjectServer_t(this);
//   }

//   /// <summary>Field number for the "entityID" field.</summary>
//   public const int EntityIDFieldNumber = 1;
//   private int entityID_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int EntityID {
//     get { return entityID_; }
//     set {
//       entityID_ = value;
//     }
//   }

//   /// <summary>Field number for the "nodeObjectID" field.</summary>
//   public const int NodeObjectIDFieldNumber = 2;
//   private int nodeObjectID_;
//   /// <summary>
//   ///node��id
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int NodeObjectID {
//     get { return nodeObjectID_; }
//     set {
//       nodeObjectID_ = value;
//     }
//   }

//   /// <summary>Field number for the "nodeCurrState" field.</summary>
//   public const int NodeCurrStateFieldNumber = 3;
//   private int nodeCurrState_;
//   /// <summary>
//   ///node�ĵ�ǰ״̬
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int NodeCurrState {
//     get { return nodeCurrState_; }
//     set {
//       nodeCurrState_ = value;
//     }
//   }

//   /// <summary>Field number for the "nodeChangeToState" field.</summary>
//   public const int NodeChangeToStateFieldNumber = 4;
//   private int nodeChangeToState_;
//   /// <summary>
//   ///�л�����һ��״̬
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int NodeChangeToState {
//     get { return nodeChangeToState_; }
//     set {
//       nodeChangeToState_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as NodeObjectServer_t);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(NodeObjectServer_t other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (EntityID != other.EntityID) return false;
//     if (NodeObjectID != other.NodeObjectID) return false;
//     if (NodeCurrState != other.NodeCurrState) return false;
//     if (NodeChangeToState != other.NodeChangeToState) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (EntityID != 0) hash ^= EntityID.GetHashCode();
//     if (NodeObjectID != 0) hash ^= NodeObjectID.GetHashCode();
//     if (NodeCurrState != 0) hash ^= NodeCurrState.GetHashCode();
//     if (NodeChangeToState != 0) hash ^= NodeChangeToState.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (NodeObjectID != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(NodeObjectID);
//     }
//     if (NodeCurrState != 0) {
//       output.WriteRawTag(24);
//       output.WriteInt32(NodeCurrState);
//     }
//     if (NodeChangeToState != 0) {
//       output.WriteRawTag(32);
//       output.WriteInt32(NodeChangeToState);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (NodeObjectID != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(NodeObjectID);
//     }
//     if (NodeCurrState != 0) {
//       output.WriteRawTag(24);
//       output.WriteInt32(NodeCurrState);
//     }
//     if (NodeChangeToState != 0) {
//       output.WriteRawTag(32);
//       output.WriteInt32(NodeChangeToState);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (EntityID != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityID);
//     }
//     if (NodeObjectID != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(NodeObjectID);
//     }
//     if (NodeCurrState != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(NodeCurrState);
//     }
//     if (NodeChangeToState != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(NodeChangeToState);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(NodeObjectServer_t other) {
//     if (other == null) {
//       return;
//     }
//     if (other.EntityID != 0) {
//       EntityID = other.EntityID;
//     }
//     if (other.NodeObjectID != 0) {
//       NodeObjectID = other.NodeObjectID;
//     }
//     if (other.NodeCurrState != 0) {
//       NodeCurrState = other.NodeCurrState;
//     }
//     if (other.NodeChangeToState != 0) {
//       NodeChangeToState = other.NodeChangeToState;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//         case 16: {
//           NodeObjectID = input.ReadInt32();
//           break;
//         }
//         case 24: {
//           NodeCurrState = input.ReadInt32();
//           break;
//         }
//         case 32: {
//           NodeChangeToState = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//         case 16: {
//           NodeObjectID = input.ReadInt32();
//           break;
//         }
//         case 24: {
//           NodeCurrState = input.ReadInt32();
//           break;
//         }
//         case 32: {
//           NodeChangeToState = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class NodeObjectInfosReq : pb::IMessage<NodeObjectInfosReq>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<NodeObjectInfosReq> _parser = new pb::MessageParser<NodeObjectInfosReq>(() => new NodeObjectInfosReq());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<NodeObjectInfosReq> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[1]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectInfosReq() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectInfosReq(NodeObjectInfosReq other) : this() {
//     dungeonID_ = other.dungeonID_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectInfosReq Clone() {
//     return new NodeObjectInfosReq(this);
//   }

//   /// <summary>Field number for the "dungeonID" field.</summary>
//   public const int DungeonIDFieldNumber = 1;
//   private string dungeonID_ = "";
//   /// <summary>
//   ///���³�ID
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public string DungeonID {
//     get { return dungeonID_; }
//     set {
//       dungeonID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as NodeObjectInfosReq);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(NodeObjectInfosReq other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (DungeonID != other.DungeonID) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (DungeonID.Length != 0) hash ^= DungeonID.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (DungeonID.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(DungeonID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (DungeonID.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(DungeonID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (DungeonID.Length != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeStringSize(DungeonID);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(NodeObjectInfosReq other) {
//     if (other == null) {
//       return;
//     }
//     if (other.DungeonID.Length != 0) {
//       DungeonID = other.DungeonID;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 10: {
//           DungeonID = input.ReadString();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 10: {
//           DungeonID = input.ReadString();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class NodeObjectInfosAck : pb::IMessage<NodeObjectInfosAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<NodeObjectInfosAck> _parser = new pb::MessageParser<NodeObjectInfosAck>(() => new NodeObjectInfosAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<NodeObjectInfosAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[2]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectInfosAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectInfosAck(NodeObjectInfosAck other) : this() {
//     errorCode_ = other.errorCode_;
//     dungeonID_ = other.dungeonID_;
//     nodeObjectInfo_ = other.nodeObjectInfo_.Clone();
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NodeObjectInfosAck Clone() {
//     return new NodeObjectInfosAck(this);
//   }

//   /// <summary>Field number for the "errorCode" field.</summary>
//   public const int ErrorCodeFieldNumber = 1;
//   private global::ErrorCode errorCode_ = global::ErrorCode.None;
//   /// <summary>
//   ///������
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::ErrorCode ErrorCode {
//     get { return errorCode_; }
//     set {
//       errorCode_ = value;
//     }
//   }

//   /// <summary>Field number for the "dungeonID" field.</summary>
//   public const int DungeonIDFieldNumber = 2;
//   private string dungeonID_ = "";
//   /// <summary>
//   ///���³�ID
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public string DungeonID {
//     get { return dungeonID_; }
//     set {
//       dungeonID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//     }
//   }

//   /// <summary>Field number for the "nodeObjectInfo" field.</summary>
//   public const int NodeObjectInfoFieldNumber = 3;
//   private static readonly pb::FieldCodec<global::NodeObjectServer_t> _repeated_nodeObjectInfo_codec
//       = pb::FieldCodec.ForMessage(26, global::NodeObjectServer_t.Parser);
//   private readonly pbc::RepeatedField<global::NodeObjectServer_t> nodeObjectInfo_ = new pbc::RepeatedField<global::NodeObjectServer_t>();
//   /// <summary>
//   ///�������е�node��Ϣ
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public pbc::RepeatedField<global::NodeObjectServer_t> NodeObjectInfo {
//     get { return nodeObjectInfo_; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as NodeObjectInfosAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(NodeObjectInfosAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (ErrorCode != other.ErrorCode) return false;
//     if (DungeonID != other.DungeonID) return false;
//     if(!nodeObjectInfo_.Equals(other.nodeObjectInfo_)) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (ErrorCode != global::ErrorCode.None) hash ^= ErrorCode.GetHashCode();
//     if (DungeonID.Length != 0) hash ^= DungeonID.GetHashCode();
//     hash ^= nodeObjectInfo_.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (DungeonID.Length != 0) {
//       output.WriteRawTag(18);
//       output.WriteString(DungeonID);
//     }
//     nodeObjectInfo_.WriteTo(output, _repeated_nodeObjectInfo_codec);
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (DungeonID.Length != 0) {
//       output.WriteRawTag(18);
//       output.WriteString(DungeonID);
//     }
//     nodeObjectInfo_.WriteTo(ref output, _repeated_nodeObjectInfo_codec);
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (ErrorCode != global::ErrorCode.None) {
//       size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
//     }
//     if (DungeonID.Length != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeStringSize(DungeonID);
//     }
//     size += nodeObjectInfo_.CalculateSize(_repeated_nodeObjectInfo_codec);
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(NodeObjectInfosAck other) {
//     if (other == null) {
//       return;
//     }
//     if (other.ErrorCode != global::ErrorCode.None) {
//       ErrorCode = other.ErrorCode;
//     }
//     if (other.DungeonID.Length != 0) {
//       DungeonID = other.DungeonID;
//     }
//     nodeObjectInfo_.Add(other.nodeObjectInfo_);
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 18: {
//           DungeonID = input.ReadString();
//           break;
//         }
//         case 26: {
//           nodeObjectInfo_.AddEntriesFrom(input, _repeated_nodeObjectInfo_codec);
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 18: {
//           DungeonID = input.ReadString();
//           break;
//         }
//         case 26: {
//           nodeObjectInfo_.AddEntriesFrom(ref input, _repeated_nodeObjectInfo_codec);
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///�����¼�
// /// </summary>
// public sealed partial class TriggerNodeObjectReq : pb::IMessage<TriggerNodeObjectReq>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<TriggerNodeObjectReq> _parser = new pb::MessageParser<TriggerNodeObjectReq>(() => new TriggerNodeObjectReq());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<TriggerNodeObjectReq> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[3]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public TriggerNodeObjectReq() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public TriggerNodeObjectReq(TriggerNodeObjectReq other) : this() {
//     entityID_ = other.entityID_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public TriggerNodeObjectReq Clone() {
//     return new TriggerNodeObjectReq(this);
//   }

//   /// <summary>Field number for the "entityID" field.</summary>
//   public const int EntityIDFieldNumber = 1;
//   private int entityID_;
//   /// <summary>
//   ///int32 taskID = 1;               //����ID
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int EntityID {
//     get { return entityID_; }
//     set {
//       entityID_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as TriggerNodeObjectReq);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(TriggerNodeObjectReq other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (EntityID != other.EntityID) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (EntityID != 0) hash ^= EntityID.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (EntityID != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityID);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(TriggerNodeObjectReq other) {
//     if (other == null) {
//       return;
//     }
//     if (other.EntityID != 0) {
//       EntityID = other.EntityID;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class TriggerNodeObjectAck : pb::IMessage<TriggerNodeObjectAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<TriggerNodeObjectAck> _parser = new pb::MessageParser<TriggerNodeObjectAck>(() => new TriggerNodeObjectAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<TriggerNodeObjectAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[4]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public TriggerNodeObjectAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public TriggerNodeObjectAck(TriggerNodeObjectAck other) : this() {
//     errorCode_ = other.errorCode_;
//     entityID_ = other.entityID_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public TriggerNodeObjectAck Clone() {
//     return new TriggerNodeObjectAck(this);
//   }

//   /// <summary>Field number for the "errorCode" field.</summary>
//   public const int ErrorCodeFieldNumber = 1;
//   private global::ErrorCode errorCode_ = global::ErrorCode.None;
//   /// <summary>
//   ///����������ɹ����᷵�ش�����
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::ErrorCode ErrorCode {
//     get { return errorCode_; }
//     set {
//       errorCode_ = value;
//     }
//   }

//   /// <summary>Field number for the "entityID" field.</summary>
//   public const int EntityIDFieldNumber = 2;
//   private int entityID_;
//   /// <summary>
//   ///���������ɵ��Ǹ�uid
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int EntityID {
//     get { return entityID_; }
//     set {
//       entityID_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as TriggerNodeObjectAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(TriggerNodeObjectAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (ErrorCode != other.ErrorCode) return false;
//     if (EntityID != other.EntityID) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (ErrorCode != global::ErrorCode.None) hash ^= ErrorCode.GetHashCode();
//     if (EntityID != 0) hash ^= EntityID.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (EntityID != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(EntityID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (EntityID != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(EntityID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (ErrorCode != global::ErrorCode.None) {
//       size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
//     }
//     if (EntityID != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityID);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(TriggerNodeObjectAck other) {
//     if (other == null) {
//       return;
//     }
//     if (other.ErrorCode != global::ErrorCode.None) {
//       ErrorCode = other.ErrorCode;
//     }
//     if (other.EntityID != 0) {
//       EntityID = other.EntityID;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 16: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 16: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///�������������͡��ڵ��״̬�ı�
// /// </summary>
// public sealed partial class NotifyNodeObjectChangedAck : pb::IMessage<NotifyNodeObjectChangedAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<NotifyNodeObjectChangedAck> _parser = new pb::MessageParser<NotifyNodeObjectChangedAck>(() => new NotifyNodeObjectChangedAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<NotifyNodeObjectChangedAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[5]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NotifyNodeObjectChangedAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NotifyNodeObjectChangedAck(NotifyNodeObjectChangedAck other) : this() {
//     nodeObjectInfo_ = other.nodeObjectInfo_.Clone();
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NotifyNodeObjectChangedAck Clone() {
//     return new NotifyNodeObjectChangedAck(this);
//   }

//   /// <summary>Field number for the "nodeObjectInfo" field.</summary>
//   public const int NodeObjectInfoFieldNumber = 1;
//   private static readonly pb::FieldCodec<global::NodeObjectServer_t> _repeated_nodeObjectInfo_codec
//       = pb::FieldCodec.ForMessage(10, global::NodeObjectServer_t.Parser);
//   private readonly pbc::RepeatedField<global::NodeObjectServer_t> nodeObjectInfo_ = new pbc::RepeatedField<global::NodeObjectServer_t>();
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public pbc::RepeatedField<global::NodeObjectServer_t> NodeObjectInfo {
//     get { return nodeObjectInfo_; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as NotifyNodeObjectChangedAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(NotifyNodeObjectChangedAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if(!nodeObjectInfo_.Equals(other.nodeObjectInfo_)) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     hash ^= nodeObjectInfo_.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     nodeObjectInfo_.WriteTo(output, _repeated_nodeObjectInfo_codec);
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     nodeObjectInfo_.WriteTo(ref output, _repeated_nodeObjectInfo_codec);
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     size += nodeObjectInfo_.CalculateSize(_repeated_nodeObjectInfo_codec);
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(NotifyNodeObjectChangedAck other) {
//     if (other == null) {
//       return;
//     }
//     nodeObjectInfo_.Add(other.nodeObjectInfo_);
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 10: {
//           nodeObjectInfo_.AddEntriesFrom(input, _repeated_nodeObjectInfo_codec);
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 10: {
//           nodeObjectInfo_.AddEntriesFrom(ref input, _repeated_nodeObjectInfo_codec);
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///���� �������
// /// </summary>
// public sealed partial class InteractionCompletedReq : pb::IMessage<InteractionCompletedReq>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<InteractionCompletedReq> _parser = new pb::MessageParser<InteractionCompletedReq>(() => new InteractionCompletedReq());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<InteractionCompletedReq> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[6]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public InteractionCompletedReq() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public InteractionCompletedReq(InteractionCompletedReq other) : this() {
//     entityID_ = other.entityID_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public InteractionCompletedReq Clone() {
//     return new InteractionCompletedReq(this);
//   }

//   /// <summary>Field number for the "entityID" field.</summary>
//   public const int EntityIDFieldNumber = 1;
//   private int entityID_;
//   /// <summary>
//   ///�ĸ�node
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int EntityID {
//     get { return entityID_; }
//     set {
//       entityID_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as InteractionCompletedReq);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(InteractionCompletedReq other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (EntityID != other.EntityID) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (EntityID != 0) hash ^= EntityID.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (EntityID != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityID);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(InteractionCompletedReq other) {
//     if (other == null) {
//       return;
//     }
//     if (other.EntityID != 0) {
//       EntityID = other.EntityID;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class InteractionCompletedAck : pb::IMessage<InteractionCompletedAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<InteractionCompletedAck> _parser = new pb::MessageParser<InteractionCompletedAck>(() => new InteractionCompletedAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<InteractionCompletedAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[7]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public InteractionCompletedAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public InteractionCompletedAck(InteractionCompletedAck other) : this() {
//     errorCode_ = other.errorCode_;
//     entityID_ = other.entityID_;
//     interBase_ = other.interBase_ != null ? other.interBase_.Clone() : null;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public InteractionCompletedAck Clone() {
//     return new InteractionCompletedAck(this);
//   }

//   /// <summary>Field number for the "errorCode" field.</summary>
//   public const int ErrorCodeFieldNumber = 1;
//   private global::ErrorCode errorCode_ = global::ErrorCode.None;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::ErrorCode ErrorCode {
//     get { return errorCode_; }
//     set {
//       errorCode_ = value;
//     }
//   }

//   /// <summary>Field number for the "entityID" field.</summary>
//   public const int EntityIDFieldNumber = 2;
//   private int entityID_;
//   /// <summary>
//   ///�ĸ�node
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int EntityID {
//     get { return entityID_; }
//     set {
//       entityID_ = value;
//     }
//   }

//   /// <summary>Field number for the "interBase" field.</summary>
//   public const int InterBaseFieldNumber = 3;
//   private global::InteractionBase interBase_;
//   /// <summary>
//   ///��������
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::InteractionBase InterBase {
//     get { return interBase_; }
//     set {
//       interBase_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as InteractionCompletedAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(InteractionCompletedAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (ErrorCode != other.ErrorCode) return false;
//     if (EntityID != other.EntityID) return false;
//     if (!object.Equals(InterBase, other.InterBase)) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (ErrorCode != global::ErrorCode.None) hash ^= ErrorCode.GetHashCode();
//     if (EntityID != 0) hash ^= EntityID.GetHashCode();
//     if (interBase_ != null) hash ^= InterBase.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (EntityID != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(EntityID);
//     }
//     if (interBase_ != null) {
//       output.WriteRawTag(26);
//       output.WriteMessage(InterBase);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (EntityID != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(EntityID);
//     }
//     if (interBase_ != null) {
//       output.WriteRawTag(26);
//       output.WriteMessage(InterBase);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (ErrorCode != global::ErrorCode.None) {
//       size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
//     }
//     if (EntityID != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityID);
//     }
//     if (interBase_ != null) {
//       size += 1 + pb::CodedOutputStream.ComputeMessageSize(InterBase);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(InteractionCompletedAck other) {
//     if (other == null) {
//       return;
//     }
//     if (other.ErrorCode != global::ErrorCode.None) {
//       ErrorCode = other.ErrorCode;
//     }
//     if (other.EntityID != 0) {
//       EntityID = other.EntityID;
//     }
//     if (other.interBase_ != null) {
//       if (interBase_ == null) {
//         InterBase = new global::InteractionBase();
//       }
//       InterBase.MergeFrom(other.InterBase);
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 16: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//         case 26: {
//           if (interBase_ == null) {
//             InterBase = new global::InteractionBase();
//           }
//           input.ReadMessage(InterBase);
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 16: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//         case 26: {
//           if (interBase_ == null) {
//             InterBase = new global::InteractionBase();
//           }
//           input.ReadMessage(InterBase);
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///֪ͨNPC�ƶ�
// /// </summary>
// public sealed partial class NotifyNpcDoActionAck : pb::IMessage<NotifyNpcDoActionAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<NotifyNpcDoActionAck> _parser = new pb::MessageParser<NotifyNpcDoActionAck>(() => new NotifyNpcDoActionAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<NotifyNpcDoActionAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::BattleverifyReflection.Descriptor.MessageTypes[8]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NotifyNpcDoActionAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NotifyNpcDoActionAck(NotifyNpcDoActionAck other) : this() {
//     entityID_ = other.entityID_;
//     actionID_ = other.actionID_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public NotifyNpcDoActionAck Clone() {
//     return new NotifyNpcDoActionAck(this);
//   }

//   /// <summary>Field number for the "entityID" field.</summary>
//   public const int EntityIDFieldNumber = 1;
//   private int entityID_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int EntityID {
//     get { return entityID_; }
//     set {
//       entityID_ = value;
//     }
//   }

//   /// <summary>Field number for the "actionID" field.</summary>
//   public const int ActionIDFieldNumber = 2;
//   private string actionID_ = "";
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public string ActionID {
//     get { return actionID_; }
//     set {
//       actionID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as NotifyNpcDoActionAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(NotifyNpcDoActionAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (EntityID != other.EntityID) return false;
//     if (ActionID != other.ActionID) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (EntityID != 0) hash ^= EntityID.GetHashCode();
//     if (ActionID.Length != 0) hash ^= ActionID.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (ActionID.Length != 0) {
//       output.WriteRawTag(18);
//       output.WriteString(ActionID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (EntityID != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(EntityID);
//     }
//     if (ActionID.Length != 0) {
//       output.WriteRawTag(18);
//       output.WriteString(ActionID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (EntityID != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(EntityID);
//     }
//     if (ActionID.Length != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeStringSize(ActionID);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(NotifyNpcDoActionAck other) {
//     if (other == null) {
//       return;
//     }
//     if (other.EntityID != 0) {
//       EntityID = other.EntityID;
//     }
//     if (other.ActionID.Length != 0) {
//       ActionID = other.ActionID;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//         case 18: {
//           ActionID = input.ReadString();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           EntityID = input.ReadInt32();
//           break;
//         }
//         case 18: {
//           ActionID = input.ReadString();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// #endregion


// #endregion Designer generated code
