// // <auto-generated>
// //     Generated by the protocol buffer compiler.  DO NOT EDIT!
// //     source: common.proto
// // </auto-generated>
// #pragma warning disable 1591, 0612, 3021
// #region Designer generated code

// using pb = global::Google.Protobuf;
// using pbc = global::Google.Protobuf.Collections;
// using pbr = global::Google.Protobuf.Reflection;
// using scg = global::System.Collections.Generic;
// /// <summary>Holder for reflection information generated from common.proto</summary>
// public static partial class CommonReflection {

//   #region Descriptor
//   /// <summary>File descriptor for common.proto</summary>
//   public static pbr::FileDescriptor Descriptor {
//     get { return descriptor; }
//   }
//   private static pbr::FileDescriptor descriptor;

//   static CommonReflection() {
//     byte[] descriptorData = global::System.Convert.FromBase64String(
//         string.Concat(
//           "Cgxjb21tb24ucHJvdG8iLwoMVmVjdG9yM0Zsb2F0EgkKAXgYASABKAISCQoB",
//           "eRgCIAEoAhIJCgF6GAMgASgCIiQKDFZlY3RvcjJGbG9hdBIJCgF4GAEgASgC",
//           "EgkKAXkYAiABKAIiLQoKVmVjdG9yM0ludBIJCgF4GAEgASgFEgkKAXkYAiAB",
//           "KAUSCQoBehgDIAEoBSIiCgpWZWN0b3IySW50EgkKAXgYASABKAUSCQoBeRgC",
//           "IAEoBSppCgpNb2R1bGVUeXBlEg4KCk1vZHVsZU5vbmUQABIPCgtNb2R1bGVM",
//           "b2dpbhABEg8KC01vZHVsZUxvYmJ5EAISEQoNTW9kdWxlRHVuZ2VvbhADEhYK",
//           "Ek1vZHVsZUJhdHRsZVZlcmlmeRAEQhdaFS4uLy4uL3NlcnZlci9wcm90b2Nv",
//           "bGIGcHJvdG8z"));
//     descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
//         new pbr::FileDescriptor[] { },
//         new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ModuleType), }, null, new pbr::GeneratedClrTypeInfo[] {
//           new pbr::GeneratedClrTypeInfo(typeof(global::Vector3Float), global::Vector3Float.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::Vector2Float), global::Vector2Float.Parser, new[]{ "X", "Y" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::Vector3Int), global::Vector3Int.Parser, new[]{ "X", "Y", "Z" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::Vector2Int), global::Vector2Int.Parser, new[]{ "X", "Y" }, null, null, null, null)
//         }));
//   }
//   #endregion

// }
// #region Enums
// public enum ModuleType {
//   [pbr::OriginalName("ModuleNone")] ModuleNone = 0,
//   /// <summary>
//   ///��½ģ��
//   /// </summary>
//   [pbr::OriginalName("ModuleLogin")] ModuleLogin = 1,
//   /// <summary>
//   ///����ģ��
//   /// </summary>
//   [pbr::OriginalName("ModuleLobby")] ModuleLobby = 2,
//   /// <summary>
//   ///���³�ģ��
//   /// </summary>
//   [pbr::OriginalName("ModuleDungeon")] ModuleDungeon = 3,
//   /// <summary>
//   ///���³�ս����֤ģ��
//   /// </summary>
//   [pbr::OriginalName("ModuleBattleVerify")] ModuleBattleVerify = 4,
// }

// #endregion

// #region Messages
// public sealed partial class Vector3Float : pb::IMessage<Vector3Float>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<Vector3Float> _parser = new pb::MessageParser<Vector3Float>(() => new Vector3Float());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<Vector3Float> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::CommonReflection.Descriptor.MessageTypes[0]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector3Float() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector3Float(Vector3Float other) : this() {
//     x_ = other.x_;
//     y_ = other.y_;
//     z_ = other.z_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector3Float Clone() {
//     return new Vector3Float(this);
//   }

//   /// <summary>Field number for the "x" field.</summary>
//   public const int XFieldNumber = 1;
//   private float x_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public float X {
//     get { return x_; }
//     set {
//       x_ = value;
//     }
//   }

//   /// <summary>Field number for the "y" field.</summary>
//   public const int YFieldNumber = 2;
//   private float y_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public float Y {
//     get { return y_; }
//     set {
//       y_ = value;
//     }
//   }

//   /// <summary>Field number for the "z" field.</summary>
//   public const int ZFieldNumber = 3;
//   private float z_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public float Z {
//     get { return z_; }
//     set {
//       z_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as Vector3Float);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(Vector3Float other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
//     if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
//     if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Z, other.Z)) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
//     if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
//     if (Z != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Z);
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (X != 0F) {
//       output.WriteRawTag(13);
//       output.WriteFloat(X);
//     }
//     if (Y != 0F) {
//       output.WriteRawTag(21);
//       output.WriteFloat(Y);
//     }
//     if (Z != 0F) {
//       output.WriteRawTag(29);
//       output.WriteFloat(Z);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (X != 0F) {
//       output.WriteRawTag(13);
//       output.WriteFloat(X);
//     }
//     if (Y != 0F) {
//       output.WriteRawTag(21);
//       output.WriteFloat(Y);
//     }
//     if (Z != 0F) {
//       output.WriteRawTag(29);
//       output.WriteFloat(Z);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (X != 0F) {
//       size += 1 + 4;
//     }
//     if (Y != 0F) {
//       size += 1 + 4;
//     }
//     if (Z != 0F) {
//       size += 1 + 4;
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(Vector3Float other) {
//     if (other == null) {
//       return;
//     }
//     if (other.X != 0F) {
//       X = other.X;
//     }
//     if (other.Y != 0F) {
//       Y = other.Y;
//     }
//     if (other.Z != 0F) {
//       Z = other.Z;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 13: {
//           X = input.ReadFloat();
//           break;
//         }
//         case 21: {
//           Y = input.ReadFloat();
//           break;
//         }
//         case 29: {
//           Z = input.ReadFloat();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 13: {
//           X = input.ReadFloat();
//           break;
//         }
//         case 21: {
//           Y = input.ReadFloat();
//           break;
//         }
//         case 29: {
//           Z = input.ReadFloat();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class Vector2Float : pb::IMessage<Vector2Float>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<Vector2Float> _parser = new pb::MessageParser<Vector2Float>(() => new Vector2Float());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<Vector2Float> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::CommonReflection.Descriptor.MessageTypes[1]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector2Float() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector2Float(Vector2Float other) : this() {
//     x_ = other.x_;
//     y_ = other.y_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector2Float Clone() {
//     return new Vector2Float(this);
//   }

//   /// <summary>Field number for the "x" field.</summary>
//   public const int XFieldNumber = 1;
//   private float x_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public float X {
//     get { return x_; }
//     set {
//       x_ = value;
//     }
//   }

//   /// <summary>Field number for the "y" field.</summary>
//   public const int YFieldNumber = 2;
//   private float y_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public float Y {
//     get { return y_; }
//     set {
//       y_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as Vector2Float);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(Vector2Float other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(X, other.X)) return false;
//     if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Y, other.Y)) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (X != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(X);
//     if (Y != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Y);
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (X != 0F) {
//       output.WriteRawTag(13);
//       output.WriteFloat(X);
//     }
//     if (Y != 0F) {
//       output.WriteRawTag(21);
//       output.WriteFloat(Y);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (X != 0F) {
//       output.WriteRawTag(13);
//       output.WriteFloat(X);
//     }
//     if (Y != 0F) {
//       output.WriteRawTag(21);
//       output.WriteFloat(Y);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (X != 0F) {
//       size += 1 + 4;
//     }
//     if (Y != 0F) {
//       size += 1 + 4;
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(Vector2Float other) {
//     if (other == null) {
//       return;
//     }
//     if (other.X != 0F) {
//       X = other.X;
//     }
//     if (other.Y != 0F) {
//       Y = other.Y;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 13: {
//           X = input.ReadFloat();
//           break;
//         }
//         case 21: {
//           Y = input.ReadFloat();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 13: {
//           X = input.ReadFloat();
//           break;
//         }
//         case 21: {
//           Y = input.ReadFloat();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class Vector3Int : pb::IMessage<Vector3Int>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<Vector3Int> _parser = new pb::MessageParser<Vector3Int>(() => new Vector3Int());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<Vector3Int> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::CommonReflection.Descriptor.MessageTypes[2]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector3Int() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector3Int(Vector3Int other) : this() {
//     x_ = other.x_;
//     y_ = other.y_;
//     z_ = other.z_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector3Int Clone() {
//     return new Vector3Int(this);
//   }

//   /// <summary>Field number for the "x" field.</summary>
//   public const int XFieldNumber = 1;
//   private int x_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int X {
//     get { return x_; }
//     set {
//       x_ = value;
//     }
//   }

//   /// <summary>Field number for the "y" field.</summary>
//   public const int YFieldNumber = 2;
//   private int y_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int Y {
//     get { return y_; }
//     set {
//       y_ = value;
//     }
//   }

//   /// <summary>Field number for the "z" field.</summary>
//   public const int ZFieldNumber = 3;
//   private int z_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int Z {
//     get { return z_; }
//     set {
//       z_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as Vector3Int);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(Vector3Int other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (X != other.X) return false;
//     if (Y != other.Y) return false;
//     if (Z != other.Z) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (X != 0) hash ^= X.GetHashCode();
//     if (Y != 0) hash ^= Y.GetHashCode();
//     if (Z != 0) hash ^= Z.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (X != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(X);
//     }
//     if (Y != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(Y);
//     }
//     if (Z != 0) {
//       output.WriteRawTag(24);
//       output.WriteInt32(Z);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (X != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(X);
//     }
//     if (Y != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(Y);
//     }
//     if (Z != 0) {
//       output.WriteRawTag(24);
//       output.WriteInt32(Z);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (X != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
//     }
//     if (Y != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
//     }
//     if (Z != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(Z);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(Vector3Int other) {
//     if (other == null) {
//       return;
//     }
//     if (other.X != 0) {
//       X = other.X;
//     }
//     if (other.Y != 0) {
//       Y = other.Y;
//     }
//     if (other.Z != 0) {
//       Z = other.Z;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           X = input.ReadInt32();
//           break;
//         }
//         case 16: {
//           Y = input.ReadInt32();
//           break;
//         }
//         case 24: {
//           Z = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           X = input.ReadInt32();
//           break;
//         }
//         case 16: {
//           Y = input.ReadInt32();
//           break;
//         }
//         case 24: {
//           Z = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class Vector2Int : pb::IMessage<Vector2Int>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<Vector2Int> _parser = new pb::MessageParser<Vector2Int>(() => new Vector2Int());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<Vector2Int> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::CommonReflection.Descriptor.MessageTypes[3]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector2Int() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector2Int(Vector2Int other) : this() {
//     x_ = other.x_;
//     y_ = other.y_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public Vector2Int Clone() {
//     return new Vector2Int(this);
//   }

//   /// <summary>Field number for the "x" field.</summary>
//   public const int XFieldNumber = 1;
//   private int x_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int X {
//     get { return x_; }
//     set {
//       x_ = value;
//     }
//   }

//   /// <summary>Field number for the "y" field.</summary>
//   public const int YFieldNumber = 2;
//   private int y_;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int Y {
//     get { return y_; }
//     set {
//       y_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as Vector2Int);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(Vector2Int other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (X != other.X) return false;
//     if (Y != other.Y) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (X != 0) hash ^= X.GetHashCode();
//     if (Y != 0) hash ^= Y.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (X != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(X);
//     }
//     if (Y != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(Y);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (X != 0) {
//       output.WriteRawTag(8);
//       output.WriteInt32(X);
//     }
//     if (Y != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(Y);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (X != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
//     }
//     if (Y != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(Vector2Int other) {
//     if (other == null) {
//       return;
//     }
//     if (other.X != 0) {
//       X = other.X;
//     }
//     if (other.Y != 0) {
//       Y = other.Y;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           X = input.ReadInt32();
//           break;
//         }
//         case 16: {
//           Y = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           X = input.ReadInt32();
//           break;
//         }
//         case 16: {
//           Y = input.ReadInt32();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// #endregion


// #endregion Designer generated code
