// // <auto-generated>
// //     Generated by the protocol buffer compiler.  DO NOT EDIT!
// //     source: lobby.proto
// // </auto-generated>
// #pragma warning disable 1591, 0612, 3021
// #region Designer generated code

// using pb = global::Google.Protobuf;
// using pbc = global::Google.Protobuf.Collections;
// using pbr = global::Google.Protobuf.Reflection;
// using scg = global::System.Collections.Generic;
// /// <summary>Holder for reflection information generated from lobby.proto</summary>
// public static partial class LobbyReflection {

//   #region Descriptor
//   /// <summary>File descriptor for lobby.proto</summary>
//   public static pbr::FileDescriptor Descriptor {
//     get { return descriptor; }
//   }
//   private static pbr::FileDescriptor descriptor;

//   static LobbyReflection() {
//     byte[] descriptorData = global::System.Convert.FromBase64String(
//         string.Concat(
//           "Cgtsb2JieS5wcm90bxoPZXJyb3Jjb2RlLnByb3RvIo8BCg1DaGFyYWN0b3JJ",
//           "bmZvEhQKDHJvbGVDb25maWdJRBgBIAEoCRINCgVsZXZlbBgCIAEoBRIqCgZl",
//           "cXVpcHMYBCADKAsyGi5DaGFyYWN0b3JJbmZvLkVxdWlwc0VudHJ5Gi0KC0Vx",
//           "dWlwc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoAzoCOAEiDwoN",
//           "RW50ZXJMb2JieVJlcSJQCg1FbnRlckxvYmJ5QWNrEh0KCWVycm9yQ29kZRgB",
//           "IAEoDjIKLkVycm9yQ29kZRIgCghjaGFySW5mbxgCIAEoCzIOLkNoYXJhY3Rv",
//           "ckluZm8iLQoSQ3JlYXRlQ2hhcmFjdG9yUmVxEhcKD3NlbFJvbGVDb25maWdJ",
//           "RBgBIAEoCSIzChJDcmVhdGVDaGFyYWN0b3JBY2sSHQoJZXJyb3JDb2RlGAEg",
//           "ASgOMgouRXJyb3JDb2RlKjEKCkxvYmJ5TXNnSUQSDgoKRW50ZXJMb2JieRAA",
//           "EhMKD0NyZWF0ZUNoYXJhY3RvchABQhdaFS4uLy4uL3NlcnZlci9wcm90b2Nv",
//           "bGIGcHJvdG8z"));
//     descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
//         new pbr::FileDescriptor[] { global::ErrorcodeReflection.Descriptor, },
//         new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LobbyMsgID), }, null, new pbr::GeneratedClrTypeInfo[] {
//           new pbr::GeneratedClrTypeInfo(typeof(global::CharactorInfo), global::CharactorInfo.Parser, new[]{ "RoleConfigID", "Level", "Equips" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
//           new pbr::GeneratedClrTypeInfo(typeof(global::EnterLobbyReq), global::EnterLobbyReq.Parser, null, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::EnterLobbyAck), global::EnterLobbyAck.Parser, new[]{ "ErrorCode", "CharInfo" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::CreateCharactorReq), global::CreateCharactorReq.Parser, new[]{ "SelRoleConfigID" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::CreateCharactorAck), global::CreateCharactorAck.Parser, new[]{ "ErrorCode" }, null, null, null, null)
//         }));
//   }
//   #endregion

// }
// #region Enums
// public enum LobbyMsgID {
//   /// <summary>
//   ///�������
//   /// </summary>
//   [pbr::OriginalName("EnterLobby")] EnterLobby = 0,
//   /// <summary>
//   ///����ɫ
//   /// </summary>
//   [pbr::OriginalName("CreateCharactor")] CreateCharactor = 1,
// }

// #endregion

// #region Messages
// public sealed partial class CharactorInfo : pb::IMessage<CharactorInfo>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<CharactorInfo> _parser = new pb::MessageParser<CharactorInfo>(() => new CharactorInfo());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<CharactorInfo> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::LobbyReflection.Descriptor.MessageTypes[0]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CharactorInfo() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CharactorInfo(CharactorInfo other) : this() {
//     roleConfigID_ = other.roleConfigID_;
//     level_ = other.level_;
//     equips_ = other.equips_.Clone();
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CharactorInfo Clone() {
//     return new CharactorInfo(this);
//   }

//   /// <summary>Field number for the "roleConfigID" field.</summary>
//   public const int RoleConfigIDFieldNumber = 1;
//   private string roleConfigID_ = "";
//   /// <summary>
//   ///��ɫ���ñ�ID
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public string RoleConfigID {
//     get { return roleConfigID_; }
//     set {
//       roleConfigID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//     }
//   }

//   /// <summary>Field number for the "level" field.</summary>
//   public const int LevelFieldNumber = 2;
//   private int level_;
//   /// <summary>
//   ///�ȼ�
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int Level {
//     get { return level_; }
//     set {
//       level_ = value;
//     }
//   }

//   /// <summary>Field number for the "equips" field.</summary>
//   public const int EquipsFieldNumber = 4;
//   private static readonly pbc::MapField<string, long>.Codec _map_equips_codec
//       = new pbc::MapField<string, long>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt64(16, 0L), 34);
//   private readonly pbc::MapField<string, long> equips_ = new pbc::MapField<string, long>();
//   /// <summary>
//   ///װ����Ϣ
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public pbc::MapField<string, long> Equips {
//     get { return equips_; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as CharactorInfo);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(CharactorInfo other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (RoleConfigID != other.RoleConfigID) return false;
//     if (Level != other.Level) return false;
//     if (!Equips.Equals(other.Equips)) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (RoleConfigID.Length != 0) hash ^= RoleConfigID.GetHashCode();
//     if (Level != 0) hash ^= Level.GetHashCode();
//     hash ^= Equips.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (RoleConfigID.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(RoleConfigID);
//     }
//     if (Level != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(Level);
//     }
//     equips_.WriteTo(output, _map_equips_codec);
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (RoleConfigID.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(RoleConfigID);
//     }
//     if (Level != 0) {
//       output.WriteRawTag(16);
//       output.WriteInt32(Level);
//     }
//     equips_.WriteTo(ref output, _map_equips_codec);
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (RoleConfigID.Length != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeStringSize(RoleConfigID);
//     }
//     if (Level != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level);
//     }
//     size += equips_.CalculateSize(_map_equips_codec);
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(CharactorInfo other) {
//     if (other == null) {
//       return;
//     }
//     if (other.RoleConfigID.Length != 0) {
//       RoleConfigID = other.RoleConfigID;
//     }
//     if (other.Level != 0) {
//       Level = other.Level;
//     }
//     equips_.Add(other.equips_);
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 10: {
//           RoleConfigID = input.ReadString();
//           break;
//         }
//         case 16: {
//           Level = input.ReadInt32();
//           break;
//         }
//         case 34: {
//           equips_.AddEntriesFrom(input, _map_equips_codec);
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 10: {
//           RoleConfigID = input.ReadString();
//           break;
//         }
//         case 16: {
//           Level = input.ReadInt32();
//           break;
//         }
//         case 34: {
//           equips_.AddEntriesFrom(ref input, _map_equips_codec);
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///�������
// /// </summary>
// public sealed partial class EnterLobbyReq : pb::IMessage<EnterLobbyReq>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<EnterLobbyReq> _parser = new pb::MessageParser<EnterLobbyReq>(() => new EnterLobbyReq());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<EnterLobbyReq> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::LobbyReflection.Descriptor.MessageTypes[1]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public EnterLobbyReq() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public EnterLobbyReq(EnterLobbyReq other) : this() {
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public EnterLobbyReq Clone() {
//     return new EnterLobbyReq(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as EnterLobbyReq);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(EnterLobbyReq other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(EnterLobbyReq other) {
//     if (other == null) {
//       return;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///������Ϣ����
// /// </summary>
// public sealed partial class EnterLobbyAck : pb::IMessage<EnterLobbyAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<EnterLobbyAck> _parser = new pb::MessageParser<EnterLobbyAck>(() => new EnterLobbyAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<EnterLobbyAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::LobbyReflection.Descriptor.MessageTypes[2]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public EnterLobbyAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public EnterLobbyAck(EnterLobbyAck other) : this() {
//     errorCode_ = other.errorCode_;
//     charInfo_ = other.charInfo_ != null ? other.charInfo_.Clone() : null;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public EnterLobbyAck Clone() {
//     return new EnterLobbyAck(this);
//   }

//   /// <summary>Field number for the "errorCode" field.</summary>
//   public const int ErrorCodeFieldNumber = 1;
//   private global::ErrorCode errorCode_ = global::ErrorCode.None;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::ErrorCode ErrorCode {
//     get { return errorCode_; }
//     set {
//       errorCode_ = value;
//     }
//   }

//   /// <summary>Field number for the "charInfo" field.</summary>
//   public const int CharInfoFieldNumber = 2;
//   private global::CharactorInfo charInfo_;
//   /// <summary>
//   ///��ɫ��Ϣ�����Ϊ�գ���ʾ�º���Ҫ������ɫ
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::CharactorInfo CharInfo {
//     get { return charInfo_; }
//     set {
//       charInfo_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as EnterLobbyAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(EnterLobbyAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (ErrorCode != other.ErrorCode) return false;
//     if (!object.Equals(CharInfo, other.CharInfo)) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (ErrorCode != global::ErrorCode.None) hash ^= ErrorCode.GetHashCode();
//     if (charInfo_ != null) hash ^= CharInfo.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (charInfo_ != null) {
//       output.WriteRawTag(18);
//       output.WriteMessage(CharInfo);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (charInfo_ != null) {
//       output.WriteRawTag(18);
//       output.WriteMessage(CharInfo);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (ErrorCode != global::ErrorCode.None) {
//       size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
//     }
//     if (charInfo_ != null) {
//       size += 1 + pb::CodedOutputStream.ComputeMessageSize(CharInfo);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(EnterLobbyAck other) {
//     if (other == null) {
//       return;
//     }
//     if (other.ErrorCode != global::ErrorCode.None) {
//       ErrorCode = other.ErrorCode;
//     }
//     if (other.charInfo_ != null) {
//       if (charInfo_ == null) {
//         CharInfo = new global::CharactorInfo();
//       }
//       CharInfo.MergeFrom(other.CharInfo);
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 18: {
//           if (charInfo_ == null) {
//             CharInfo = new global::CharactorInfo();
//           }
//           input.ReadMessage(CharInfo);
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//         case 18: {
//           if (charInfo_ == null) {
//             CharInfo = new global::CharactorInfo();
//           }
//           input.ReadMessage(CharInfo);
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///������ɫ
// /// </summary>
// public sealed partial class CreateCharactorReq : pb::IMessage<CreateCharactorReq>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<CreateCharactorReq> _parser = new pb::MessageParser<CreateCharactorReq>(() => new CreateCharactorReq());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<CreateCharactorReq> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::LobbyReflection.Descriptor.MessageTypes[3]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CreateCharactorReq() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CreateCharactorReq(CreateCharactorReq other) : this() {
//     selRoleConfigID_ = other.selRoleConfigID_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CreateCharactorReq Clone() {
//     return new CreateCharactorReq(this);
//   }

//   /// <summary>Field number for the "selRoleConfigID" field.</summary>
//   public const int SelRoleConfigIDFieldNumber = 1;
//   private string selRoleConfigID_ = "";
//   /// <summary>
//   ///ѡ���
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public string SelRoleConfigID {
//     get { return selRoleConfigID_; }
//     set {
//       selRoleConfigID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as CreateCharactorReq);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(CreateCharactorReq other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (SelRoleConfigID != other.SelRoleConfigID) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (SelRoleConfigID.Length != 0) hash ^= SelRoleConfigID.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (SelRoleConfigID.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(SelRoleConfigID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (SelRoleConfigID.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(SelRoleConfigID);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (SelRoleConfigID.Length != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeStringSize(SelRoleConfigID);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(CreateCharactorReq other) {
//     if (other == null) {
//       return;
//     }
//     if (other.SelRoleConfigID.Length != 0) {
//       SelRoleConfigID = other.SelRoleConfigID;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 10: {
//           SelRoleConfigID = input.ReadString();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 10: {
//           SelRoleConfigID = input.ReadString();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// /// <summary>
// ///�����Ƿ�ɹ������ʧ���������Э�飬����ɹ�����EnterLobbyAck��Э��
// /// </summary>
// public sealed partial class CreateCharactorAck : pb::IMessage<CreateCharactorAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<CreateCharactorAck> _parser = new pb::MessageParser<CreateCharactorAck>(() => new CreateCharactorAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<CreateCharactorAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::LobbyReflection.Descriptor.MessageTypes[4]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CreateCharactorAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CreateCharactorAck(CreateCharactorAck other) : this() {
//     errorCode_ = other.errorCode_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public CreateCharactorAck Clone() {
//     return new CreateCharactorAck(this);
//   }

//   /// <summary>Field number for the "errorCode" field.</summary>
//   public const int ErrorCodeFieldNumber = 1;
//   private global::ErrorCode errorCode_ = global::ErrorCode.None;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::ErrorCode ErrorCode {
//     get { return errorCode_; }
//     set {
//       errorCode_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as CreateCharactorAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(CreateCharactorAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (ErrorCode != other.ErrorCode) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (ErrorCode != global::ErrorCode.None) hash ^= ErrorCode.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (ErrorCode != global::ErrorCode.None) {
//       size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(CreateCharactorAck other) {
//     if (other == null) {
//       return;
//     }
//     if (other.ErrorCode != global::ErrorCode.None) {
//       ErrorCode = other.ErrorCode;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// #endregion


// #endregion Designer generated code
