// // <auto-generated>
// //     Generated by the protocol buffer compiler.  DO NOT EDIT!
// //     source: login.proto
// // </auto-generated>
// #pragma warning disable 1591, 0612, 3021
// #region Designer generated code

// using pb = global::Google.Protobuf;
// using pbc = global::Google.Protobuf.Collections;
// using pbr = global::Google.Protobuf.Reflection;
// using scg = global::System.Collections.Generic;
// /// <summary>Holder for reflection information generated from login.proto</summary>
// public static partial class LoginReflection {

//   #region Descriptor
//   /// <summary>File descriptor for login.proto</summary>
//   public static pbr::FileDescriptor Descriptor {
//     get { return descriptor; }
//   }
//   private static pbr::FileDescriptor descriptor;

//   static LoginReflection() {
//     byte[] descriptorData = global::System.Convert.FromBase64String(
//         string.Concat(
//           "Cgtsb2dpbi5wcm90bxoPZXJyb3Jjb2RlLnByb3RvIhkKCExvZ2luUmVxEg0K",
//           "BXRva2VuGAEgASgJIikKCExvZ2luQWNrEh0KCWVycm9yQ29kZRgBIAEoDjIK",
//           "LkVycm9yQ29kZSorCgpMb2dpbk1zZ0lEEhIKDkxvZ2luTXNnSUROb25lEAAS",
//           "CQoFTG9naW4QAUIXWhUuLi8uLi9zZXJ2ZXIvcHJvdG9jb2xiBnByb3RvMw=="));
//     descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
//         new pbr::FileDescriptor[] { global::ErrorcodeReflection.Descriptor, },
//         new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LoginMsgID), }, null, new pbr::GeneratedClrTypeInfo[] {
//           new pbr::GeneratedClrTypeInfo(typeof(global::LoginReq), global::LoginReq.Parser, new[]{ "Token" }, null, null, null, null),
//           new pbr::GeneratedClrTypeInfo(typeof(global::LoginAck), global::LoginAck.Parser, new[]{ "ErrorCode" }, null, null, null, null)
//         }));
//   }
//   #endregion

// }
// #region Enums
// public enum LoginMsgID {
//   [pbr::OriginalName("LoginMsgIDNone")] None = 0,
//   [pbr::OriginalName("Login")] Login = 1,
// }

// #endregion

// #region Messages
// /// <summary>
// ///��ʱ��½���Ժ��������������
// /// </summary>
// public sealed partial class LoginReq : pb::IMessage<LoginReq>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<LoginReq> _parser = new pb::MessageParser<LoginReq>(() => new LoginReq());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<LoginReq> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::LoginReflection.Descriptor.MessageTypes[0]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public LoginReq() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public LoginReq(LoginReq other) : this() {
//     token_ = other.token_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public LoginReq Clone() {
//     return new LoginReq(this);
//   }

//   /// <summary>Field number for the "token" field.</summary>
//   public const int TokenFieldNumber = 1;
//   private string token_ = "";
//   /// <summary>
//   ///һ��Ψһ��key,�磺������Ψһ�豸��ţ������û���
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public string Token {
//     get { return token_; }
//     set {
//       token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as LoginReq);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(LoginReq other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (Token != other.Token) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (Token.Length != 0) hash ^= Token.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (Token.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(Token);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (Token.Length != 0) {
//       output.WriteRawTag(10);
//       output.WriteString(Token);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (Token.Length != 0) {
//       size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(LoginReq other) {
//     if (other == null) {
//       return;
//     }
//     if (other.Token.Length != 0) {
//       Token = other.Token;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 10: {
//           Token = input.ReadString();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 10: {
//           Token = input.ReadString();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// public sealed partial class LoginAck : pb::IMessage<LoginAck>
// #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     , pb::IBufferMessage
// #endif
// {
//   private static readonly pb::MessageParser<LoginAck> _parser = new pb::MessageParser<LoginAck>(() => new LoginAck());
//   private pb::UnknownFieldSet _unknownFields;
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pb::MessageParser<LoginAck> Parser { get { return _parser; } }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public static pbr::MessageDescriptor Descriptor {
//     get { return global::LoginReflection.Descriptor.MessageTypes[1]; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   pbr::MessageDescriptor pb::IMessage.Descriptor {
//     get { return Descriptor; }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public LoginAck() {
//     OnConstruction();
//   }

//   partial void OnConstruction();

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public LoginAck(LoginAck other) : this() {
//     errorCode_ = other.errorCode_;
//     _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public LoginAck Clone() {
//     return new LoginAck(this);
//   }

//   /// <summary>Field number for the "errorCode" field.</summary>
//   public const int ErrorCodeFieldNumber = 1;
//   private global::ErrorCode errorCode_ = global::ErrorCode.None;
//   /// <summary>
//   /// int64 playerID = 2;             //��ҵ�ΨһID
//   /// string lobbyServerIP = 3;       //������������IP
//   /// int32 lobbyPort = 4;            //�����������Ķ˿�
//   /// string dungeonServerIP = 5;     //���³Ƿ�������ip
//   /// int32 dungeonPort = 6;          //���³Ƿ������Ķ˿�
//   /// </summary>
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public global::ErrorCode ErrorCode {
//     get { return errorCode_; }
//     set {
//       errorCode_ = value;
//     }
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override bool Equals(object other) {
//     return Equals(other as LoginAck);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public bool Equals(LoginAck other) {
//     if (ReferenceEquals(other, null)) {
//       return false;
//     }
//     if (ReferenceEquals(other, this)) {
//       return true;
//     }
//     if (ErrorCode != other.ErrorCode) return false;
//     return Equals(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override int GetHashCode() {
//     int hash = 1;
//     if (ErrorCode != global::ErrorCode.None) hash ^= ErrorCode.GetHashCode();
//     if (_unknownFields != null) {
//       hash ^= _unknownFields.GetHashCode();
//     }
//     return hash;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public override string ToString() {
//     return pb::JsonFormatter.ToDiagnosticString(this);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void WriteTo(pb::CodedOutputStream output) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     output.WriteRawMessage(this);
//   #else
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(output);
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
//     if (ErrorCode != global::ErrorCode.None) {
//       output.WriteRawTag(8);
//       output.WriteEnum((int) ErrorCode);
//     }
//     if (_unknownFields != null) {
//       _unknownFields.WriteTo(ref output);
//     }
//   }
//   #endif

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public int CalculateSize() {
//     int size = 0;
//     if (ErrorCode != global::ErrorCode.None) {
//       size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ErrorCode);
//     }
//     if (_unknownFields != null) {
//       size += _unknownFields.CalculateSize();
//     }
//     return size;
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(LoginAck other) {
//     if (other == null) {
//       return;
//     }
//     if (other.ErrorCode != global::ErrorCode.None) {
//       ErrorCode = other.ErrorCode;
//     }
//     _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
//   }

//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   public void MergeFrom(pb::CodedInputStream input) {
//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//     input.ReadRawMessage(this);
//   #else
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//       }
//     }
//   #endif
//   }

//   #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
//   [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
//   [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
//   void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
//     uint tag;
//     while ((tag = input.ReadTag()) != 0) {
//       switch(tag) {
//         default:
//           _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
//           break;
//         case 8: {
//           ErrorCode = (global::ErrorCode) input.ReadEnum();
//           break;
//         }
//       }
//     }
//   }
//   #endif

// }

// #endregion


// #endregion Designer generated code
