// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

struct MeshProperties
{
    float4x4 mat;
};

StructuredBuffer<MeshProperties> _Properties;
AppendStructuredBuffer<uint> _VisibleInstances;

[numthreads(64,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    //uint numStructs;
    //uint stride;
    //_Properties.GetDimensions(numStructs, stride);
    if(id.x < 3)
        _VisibleInstances.Append(id.x);
}